<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Services\Slugger;
final class AdminController extends BaseController
{
 public function dashboard():string{$counts=$this->pdo->query("SELECT COUNT(*) total,SUM(status='published') published,SUM(status='draft') drafts,SUM(status='scheduled') scheduled FROM posts WHERE deleted_at IS NULL")->fetch();return $this->view('admin/dashboard',['title'=>'Dashboard','counts'=>$counts,'items'=>array_slice($this->posts->adminList(),0,6)],'admin');}
 public function posts():string{return $this->view('admin/posts',['title'=>'Posts','items'=>$this->posts->adminList()],'admin');}
 public function create():string{return $this->view('admin/editor',['title'=>'New post','post'=>null,'categories'=>$this->categories()],'admin');}
 public function edit(string $id):string{$post=$this->posts->adminFind((int)$id);if(!$post){http_response_code(404);return $this->view('errors/404',['title'=>'Post not found']);}return $this->view('admin/editor',['title'=>'Edit post','post'=>$post,'categories'=>$this->categories()],'admin');}
 public function store():never{$this->csrf();$this->save(null);}
 public function update(string $id):never{$this->csrf();$this->save((int)$id);}
 public function delete(string $id):never{$this->csrf();$this->pdo->prepare('UPDATE posts SET deleted_at=NOW() WHERE id=?')->execute([(int)$id]);$this->audit('delete','post',(int)$id);$this->clearCache();$this->redirect('admin/posts');}
 public function publish(string $id):never{$this->csrf();$this->pdo->prepare("UPDATE posts SET status='published',published_at=COALESCE(published_at,NOW()),updated_at=NOW() WHERE id=?")->execute([(int)$id]);$this->audit('publish','post',(int)$id);$this->clearCache();$this->redirect('admin/posts/'.$id.'/edit');}
 public function settings():string{return $this->view('admin/settings',['title'=>'Settings','values'=>$this->settings->all()],'admin');}
 public function saveSettings():never{$this->csrf();$allowed=['site_name','site_tagline','full_name','professional_title','bio','company','location','email','website','github','linkedin','x','facebook','about_markdown'];$data=[];foreach($allowed as $k)if(isset($_POST[$k]))$data[$k]=mb_substr(trim((string)$_POST[$k]),0,$k==='about_markdown'?50000:500);$this->settings->save($data);$this->clearCache();$this->redirect('admin/settings');}
 private function save(?int $id):never{$title=trim((string)($_POST['title']??''));$markdown=(string)($_POST['markdown_content']??'');if($title===''||$markdown===''||mb_strlen($markdown)>500000){$_SESSION['_error']='Title and content are required; content must be under 500 KB.';$this->redirect($id?'admin/posts/'.$id.'/edit':'admin/posts/create');}$slug=Slugger::make($_POST['slug']?:$title);$status=in_array($_POST['status']??'draft',['draft','scheduled','published','archived'],true)?$_POST['status']:'draft';$rendered=$this->markdown->render($markdown);$values=[$title,$slug,trim((string)($_POST['excerpt']??'')),$markdown,$rendered,$status,$_SESSION['user']['id'],($_POST['category_id']??'')?:null,trim((string)($_POST['meta_title']??''))?:null,trim((string)($_POST['meta_description']??''))?:null,trim((string)($_POST['canonical_url']??''))?:null,isset($_POST['robots_index'])?1:0,isset($_POST['robots_follow'])?1:0,($_POST['scheduled_at']??'')?:null];if($id){$sql='UPDATE posts SET title=?,slug=?,excerpt=?,markdown_content=?,rendered_html_cache=?,status=?,author_id=?,category_id=?,meta_title=?,meta_description=?,canonical_url=?,robots_index=?,robots_follow=?,scheduled_at=?,published_at=IF(?="published",COALESCE(published_at,NOW()),published_at),updated_at=NOW() WHERE id=?';$values[]=$status;$values[]=$id;}else{$sql='INSERT INTO posts(title,slug,excerpt,markdown_content,rendered_html_cache,status,author_id,category_id,meta_title,meta_description,canonical_url,robots_index,robots_follow,scheduled_at,published_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,IF(?="published",NOW(),NULL),NOW(),NOW())';$values[]=$status;}$this->pdo->prepare($sql)->execute($values);$postId=$id?:((int)$this->pdo->lastInsertId());$this->audit($id?'update':'create','post',$postId);$this->clearCache();$this->redirect('admin/posts/'.$postId.'/edit');}
 private function categories():array{return $this->pdo->query('SELECT id,name FROM categories ORDER BY name')->fetchAll();}
 private function audit(string $action,string $type,int $id):void{$this->pdo->prepare('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,ip_hash,created_at) VALUES(?,?,?,?,?,NOW())')->execute([$_SESSION['user']['id'],$action,$type,$id,hash('sha256',$_SERVER['REMOTE_ADDR']??'unknown')]);}
 private function clearCache():void{foreach(glob(BASE_PATH.'/storage/cache/page-*.cache')?:[] as $f)@unlink($f);}
}
