<?php
declare(strict_types=1);
namespace App\Controllers;
final class PublicController extends BaseController
{
 public function home():string{$about=$this->settings->allPublic()['about_markdown']??"# About me\n\nI'm **Sathira Sri Sathsara**, a software engineer focused on backend development. I build secure, maintainable systems and polished web products.\n\n## What I work with\n\n- PHP and MySQL application architecture\n- REST APIs and integrations\n- Secure, accessible user experiences\n- Performance and technical SEO";return $this->view('public/home',['title'=>'About me','description'=>$this->config['profile']['bio'],'html'=>$this->markdown->render($about),'canonical'=>url('/')]);}
 public function blog(?string $page=null):string{$n=max(1,(int)($page??$_GET['page']??1));$q=mb_substr(trim((string)($_GET['q']??'')),0,100);$data=$this->posts->paginate($n,9,$q);return $this->view('public/blog',['title'=>'Blog','description'=>'Articles about software engineering and backend development.','pagination'=>$data,'query'=>$q,'canonical'=>url($n>1?'blog/page/'.$n:'blog')]);}
 public function post(string $slug):string{$post=$this->posts->findPublished($slug);if(!$post){http_response_code(404);return $this->view('errors/404',['title'=>'Article not found']);}$post['rendered']=$post['rendered_html_cache']?:$this->markdown->render($post['markdown_content']);$post['reading_time']=$this->markdown->readingMinutes($post['markdown_content']);return $this->view('public/post',['title'=>$post['meta_title']?:$post['title'],'description'=>$post['meta_description']?:$post['excerpt'],'post'=>$post,'adjacent'=>$this->posts->adjacent($post),'canonical'=>$post['canonical_url']?:url('blog/'.$post['slug'])]);}
 public function category(string $slug):string{$p=$this->posts->paginate(max(1,(int)($_GET['page']??1)),9,'',$slug);return $this->view('public/blog',['title'=>'Category','description'=>'Posts in this category.','pagination'=>$p,'query'=>'','canonical'=>url('category/'.$slug)]);}
 public function tag(string $slug):string{$p=$this->posts->paginate(max(1,(int)($_GET['page']??1)),9,'',null,$slug);return $this->view('public/blog',['title'=>'Tag','description'=>'Posts with this tag.','pagination'=>$p,'query'=>'','canonical'=>url('tag/'.$slug)]);}
 public function rss():string{header('Content-Type: application/rss+xml; charset=utf-8');$items=$this->posts->recent(25);return '<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>'.e($this->config['profile']['name']).'</title><link>'.e(url()).'</link><description>Software engineering articles</description>'.implode('',array_map(fn($p)=>'<item><title>'.e($p['title']).'</title><link>'.e(url('blog/'.$p['slug'])).'</link><guid>'.e(url('blog/'.$p['slug'])).'</guid><pubDate>'.date(DATE_RSS,strtotime($p['published_at'])).'</pubDate></item>',$items)).'</channel></rss>';}
 public function sitemap():string{header('Content-Type: application/xml; charset=utf-8');$items=$this->posts->recent(500);$urls=['','about','blog'];foreach($items as $p)$urls[]='blog/'.$p['slug'];return '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'.implode('',array_map(fn($u)=>'<url><loc>'.e(url($u)).'</loc></url>',$urls)).'</urlset>';}
 public function robots():string{header('Content-Type: text/plain');return "User-agent: *\nAllow: /\nDisallow: /admin/\nSitemap: ".url('sitemap.xml')."\n";}
 public function llms():string{header('Content-Type: text/plain');return "# ".$this->config['profile']['name']."\n\n- Home: ".url()."\n- About: ".url('about')."\n- Blog: ".url('blog')."\n- RSS: ".url('rss.xml')."\n- Sitemap: ".url('sitemap.xml')."\n- Contact: ".$this->config['profile']['email']."\n";}
 public function manifest():string{header('Content-Type: application/manifest+json');return json_encode(['name'=>$this->config['profile']['name'],'short_name'=>'Sathira','start_url'=>'/','display'=>'standalone','background_color'=>'#090b10','theme_color'=>'#7c6cff'],JSON_UNESCAPED_SLASHES);}
 public function health():string{header('Content-Type: application/json');try{$this->pdo->query('SELECT 1');return json_encode(['status'=>'ok']);}catch(\Throwable){http_response_code(503);return json_encode(['status'=>'unavailable']);}}
}
